export const Hashtags = [
  { name: 'JIMIN', char: '#JIMIN' },
  { name: '지민', char: '#지민' },
  { name: '박지민', char: '#박지민' },
  { name: 'JIN', char: '#JIN' },
  { name: '진', char: '#진' },
  { name: '김석진', char: '#김석진' },
  { name: 'V', char: '#V' },
  { name: '뷔', char: '#뷔' },
  { name: '김태형', char: '#김태형' },
  { name: 'JHOPE', char: '#JHOPE' },
  { name: '제이홉', char: '#제이홉' },
  { name: '정호석', char: '#정호석' },
  { name: 'JUNGKOOK', char: '#JUNGKOOK' },
  { name: '정국', char: '#정국' },
  { name: '전정국', char: '#전정국' },
  { name: 'SUGAR', char: '#SUGAR' },
  { name: '슈가', char: '#슈가' },
  { name: '민윤기', char: '#민윤기' },
  { name: 'RM', char: '#RM' },
  { name: '랩몬스터', char: '#랩몬스터' },
  { name: '김남준', char: '#김남준' },
];
